### ISSUE TITLE
Input types anpassen

### ISSUE THREAD

**Issue by MGZeroes** [HKA-Basketball/vs1lab#4]
Input Elemente zu passenden Datentypen anpassen.
Z.B. longtitude und latitude als double bzw. number.

**Comment by MGZeroes** [comment]
https://developer.mozilla.org/de/docs/Web/HTML/Element/Input

**Comment by lorenz-lb** [comment]
Hat keine Vorteile da trotzdem Buchstaben eingegeben werden können. Zusätzlich müsste sich dann mit Hilfe von CSS um die Up-Down Buttons gekümmert werden, da diese keinen Benefit bringen würden.

![image](https://user-images.githubusercontent.com/35742529/137478626-84f2185e-b72a-4ee7-8e81-a6175d2e0b8e.png)
